services:
  db:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "${INITIAL_DATABASE_PASSWORD}"
    env_file:
      - .env
  initdb:
    image: "${INIT_IMAGE}"
    command: /run.sh init
    env_file:
      - .env

# Example of .env file
#
# INIT_IMAGE=initdb
# INITIAL_DATABASE_USER=postgres
# INITIAL_DATABASE_PASSWORD=...
# PAPERMERGE_DATABASE_HOST=postgres
# PAPERMERGE_DATABASE_USER=www3_user
# PAPERMERGE_DATABASE_NAME=www3_db
# PAPERMERGE_DATABASE_PASSWORD=...
#

volumes:
  postgres_data: